### ISSUE TITLE
Unable to run rabbitmq worker

### ISSUE THREAD

**Issue by the-dagger** [Cloud-CV/EvalAI#1201]
Upon trying to run the rabbitmq worker, an error is thrown.

```
python scripts/workers/submission_worker.py
[2017-08-22 07:50:50] INFO Using /var/folders/km/885chd6n6gn3wfs1cwzcv0yh0000gn/T/tmpU_HP_Y as temp directory to store data
[2017-08-22 07:50:50] INFO Connecting to ::1:5672
[2017-08-22 07:50:50] WARNING Connection to ::1:5672 failed: [Errno 61] Connection refused
[2017-08-22 07:50:50] INFO Connecting to 127.0.0.1:5672
[2017-08-22 07:50:50] WARNING Connection to 127.0.0.1:5672 failed: [Errno 61] Connection refused
[2017-08-22 07:50:50] WARNING Could not connect, 0 attempts left
Traceback (most recent call last):
  File "scripts/workers/submission_worker.py", line 519, in <module>
    main()
  File "scripts/workers/submission_worker.py", line 476, in main
    host=settings.RABBITMQ_PARAMETERS['HOST'], heartbeat_interval=0))
  File "/Users/harshit/Desktop/OSProjects/EvalAI/venv/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 339, in __init__
    self._process_io_for_connection_setup()
  File "/Users/harshit/Desktop/OSProjects/EvalAI/venv/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 374, in _process_io_for_connection_setup
    self._open_error_result.is_ready)
  File "/Users/harshit/Desktop/OSProjects/EvalAI/venv/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 395, in _flush_output
    raise exceptions.ConnectionClosed()
pika.exceptions.ConnectionClosed
```

The reason for this error is that the dev server is running on port  `8000` whereas rabbitmq is listening for changes on `5672`.

**Comment by taranjeet** [comment]
Rabbit mq runs listens on port 5672. Worker is a normal python script which does not runs or binds on any port.

You are actually a bit confused here.Worker when starts tries to make connection with the app(running on port 8000 generally) and rabbit mq (runs on port 5672). I guess you need to install rabbit mq.

@the-dagger

**Comment by the-dagger** [comment]
@taranjeet Oh I see.
Thanks for the detailed explanation, I'll try to read up a bit on rabbitmq and retry this. 👍

**Comment by aayusharora** [comment]
This can be closed I guess :) @the-dagger please reopen if it does not work for you.
