### ISSUE TITLE
Update Profile not working 

### ISSUE THREAD

**Issue by gautamjajoo** [Cloud-CV/EvalAI#3279]
The users are not able to update the profile on the new frontend. Error 400 is popping up.

@Ram81 @RishabhJain2018 

![Screenshot from 2021-03-02 23-39-00](https://user-images.githubusercontent.com/24366008/109694152-7b6af600-7bb0-11eb-9a83-316c2298bd1f.png)

**Comment by Alabhya268** [comment]
@gautamjajoo , In frontendv2 updating profile is working fine with me. Could you please more elaborate on how it happened.

**Comment by gautamjajoo** [comment]
@Alabhya268 I was updating the profile by adding name/links but the changes were not displayed and error 400 was showing up.

**Comment by Alabhya268** [comment]
@gautamjajoo , It turned out trying to update ``` Affiliated to``` is causing this issue, Everything else is working fine.

**Comment by Alabhya268** [comment]
I will try to fix this issue.

**Comment by Alabhya268** [comment]
@gautamjajoo @rishabhbhardwaj @Ram81 

In accounts models.py affiliate is required field, we can simply fix this issue by allowing it to be blank but while running migrations we need secret key. Please tell me what should be done next.

**Comment by Ram81** [comment]
>we need secret key.
@Alabhya268  there is no secret key needed for generating migrations. You can just update the model file and generate a migration file from that. Let me know if you have any doubts

**Comment by Alabhya268** [comment]
@Ram81 , I am getting this error when generating migrations. Please have a look.

(venv) alabhya@alabhya-OMEN-by-HP-Laptop-15-dc0xxx:/media/alabhya/DATA4/PROJECTS/Open Source/EvalAI$ python manage.py makemigrations accounts
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/media/alabhya/DATA4/PROJECTS/Open Source/EvalAI/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/media/alabhya/DATA4/PROJECTS/Open Source/EvalAI/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/media/alabhya/DATA4/PROJECTS/Open Source/EvalAI/venv/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/media/alabhya/DATA4/PROJECTS/Open Source/EvalAI/venv/lib/python3.8/site-packages/django/core/management/base.py", line 368, in execute
    self.check()
  File "/media/alabhya/DATA4/PROJECTS/Open Source/EvalAI/venv/lib/python3.8/site-packages/django/core/management/base.py", line 392, in check
    all_issues = checks.run_checks(
  File "/media/alabhya/DATA4/PROJECTS/Open Source/EvalAI/venv/lib/python3.8/site-packages/django/core/checks/registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/media/alabhya/DATA4/PROJECTS/Open Source/EvalAI/venv/lib/python3.8/site-packages/django/core/checks/urls.py", line 10, in check_url_config
    if getattr(settings, 'ROOT_URLCONF', None):
  File "/media/alabhya/DATA4/PROJECTS/Open Source/EvalAI/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/media/alabhya/DATA4/PROJECTS/Open Source/EvalAI/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/media/alabhya/DATA4/PROJECTS/Open Source/EvalAI/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 189, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

**Comment by Ram81** [comment]
@Alabhya268 are you running EvalAI using `docker-compose`? If yes, could you try exec'ing into the django docker container and run migrations again to see if you face this issue.

**Comment by RishabhJain2018** [comment]
Closing this since we are not working on Frontend_v2
