### ISSUE TITLE
gulp watch command failing when trying to run gulp dev again and again

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#331]
See the error below. Let me know if anyone else is facing this issue. 
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: watch /Users/deshraj/Documents/EvalAI/frontend/dist/css ENOENT
    at exports._errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1305:19)
    at Object.fs.watch (fs.js:1330:11)
    at Gaze._watchDir (/Users/deshraj/Documents/EvalAI/node_modules/gaze/lib/gaze.js:289:30)
    at /Users/deshraj/Documents/EvalAI/node_modules/gaze/lib/gaze.js:358:10
    at iterate (/Users/deshraj/Documents/EvalAI/node_modules/gaze/lib/helper.js:52:5)
    at /Users/deshraj/Documents/EvalAI/node_modules/gaze/lib/helper.js:61:11
    at /Users/deshraj/Documents/EvalAI/node_modules/gaze/lib/gaze.js:420:5
    at iterate (/Users/deshraj/Documents/EvalAI/node_modules/gaze/lib/helper.js:52:5)
    at /Users/deshraj/Documents/EvalAI/node_modules/gaze/lib/helper.js:61:11
    at /Users/deshraj/Documents/EvalAI/node_modules/gaze/lib/gaze.js:420:5
    at iterate (/Users/deshraj/Documents/EvalAI/node_modules/gaze/lib/helper.js:52:5)
    at /Users/deshraj/Documents/EvalAI/node_modules/gaze/lib/helper.js:61:11
    at /Users/deshraj/Documents/EvalAI/node_modules/gaze/lib/gaze.js:420:5
    at iterate (/Users/deshraj/Documents/EvalAI/node_modules/gaze/lib/helper.js:52:5)
    at Object.forEachSeries (/Users/deshraj/Documents/EvalAI/node_modules/gaze/lib/helper.js:66:3)
[1]-  Killed: 9               gulp watch
```

**Comment by RishabhJain2018** [comment]
@deshraj Please check that `sass` is installed or not?? Also look for the `ruby` version.

**Comment by anweshknayak** [comment]
@aka-jain facing the same error . any fix ?

**Comment by aka-jain** [comment]
@deshraj : thanks to mention this bug. Anyone intereseted to solve this issue?

Basically, this is due to delete task of gulp which is deleting files while watch task correspondingly check for those  files which doesn't exist as gulp dev also runs del task. So need to handle watch task.

Please go through this link to solve this issue.
http://stackoverflow.com/questions/35733090/gulp-watch-delete-files

**Comment by anweshknayak** [comment]
@aka-jain since this is creating problem for me. Can I fix this ?

**Comment by aka-jain** [comment]
@anweshknayak : sure, go ahead.

**Comment by aka-jain** [comment]
@deshraj , @anweshknayak: one important thing don't run dev again and again, it is only made to run once when you start developement and left everything on watch task.

**Comment by deshraj** [comment]
@aka-jain @anweshknayak I am still facing the same error. Please see the log below: 

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: watch /Users/deshraj/Documents/EvalAI/frontend/dist/images ENOENT
    at exports._errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1305:19)
    at Object.fs.watch (fs.js:1330:11)
    at Gaze._watchDir (/Users/deshraj/Documents/EvalAI/node_modules/gaze/lib/gaze.js:289:30)
    at /Users/deshraj/Documents/EvalAI/node_modules/gaze/lib/gaze.js:358:10
    at iterate (/Users/deshraj/Documents/EvalAI/node_modules/gaze/lib/helper.js:52:5)
    at /Users/deshraj/Documents/EvalAI/node_modules/gaze/lib/helper.js:61:11
    at /Users/deshraj/Documents/EvalAI/node_modules/gaze/lib/gaze.js:420:5
    at iterate (/Users/deshraj/Documents/EvalAI/node_modules/gaze/lib/helper.js:52:5)
    at /Users/deshraj/Documents/EvalAI/node_modules/gaze/lib/helper.js:61:11
    at /Users/deshraj/Documents/EvalAI/node_modules/gaze/lib/gaze.js:420:5
    at iterate (/Users/deshraj/Documents/EvalAI/node_modules/gaze/lib/helper.js:52:5)
    at /Users/deshraj/Documents/EvalAI/node_modules/gaze/lib/helper.js:61:11
    at /Users/deshraj/Documents/EvalAI/node_modules/gaze/lib/gaze.js:420:5
    at iterate (/Users/deshraj/Documents/EvalAI/node_modules/gaze/lib/helper.js:52:5)
    at /Users/deshraj/Documents/EvalAI/node_modules/gaze/lib/helper.js:61:11
```

**Comment by aka-jain** [comment]
@anweshknayak : please look at it once again? Maybe the path thing makes it wrong

**Comment by anweshknayak** [comment]
Yes something to do with the base path. Will fix it.

**Comment by dexter1691** [comment]
@anweshknayak: Assigning it to you. To better analyze work-loads.

**Comment by anweshknayak** [comment]
@dexter1691 I have already fixed this . #379

**Comment by deshraj** [comment]
Closing it. :-)
