### ISSUE TITLE
Fail to upload challenge zip file

### ISSUE THREAD

**Issue by hadibokaei** [Cloud-CV/EvalAI#3585]
Hello
I am new to evalAI and I have reviewed its features. Thanks for the great platform.
I have installed it on a server using docker and I want to access it through the valid IP. Everything is OK except uploading a challenge zip file to create a new challenge. When I upload the zip file the following error is appeared in the log:

```
django_1           | [2021-08-30 09:36:56] ERROR A server error occured while processing zip file. Please try again!
django_1           | Traceback (most recent call last):
django_1           |   File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 170, in _new_conn
django_1           |     (self._dns_host, self.port), self.timeout, **extra_kw
django_1           |   File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 96, in create_connection
django_1           |     raise err
django_1           |   File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 86, in create_connection
django_1           |     sock.connect(sa)
django_1           | TimeoutError: [Errno 110] Connection timed out
django_1           |
django_1           | During handling of the above exception, another exception occurred:
django_1           |
django_1           | Traceback (most recent call last):
django_1           |   File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
django_1           |     chunked=chunked,
django_1           |   File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 394, in _make_request
django_1           |     conn.request(method, url, **httplib_request_kw)
django_1           |   File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 234, in request
django_1           |     super(HTTPConnection, self).request(method, url, body=body, headers=headers)
django_1           |   File "/usr/local/lib/python3.7/http/client.py", line 1252, in request
django_1           |     self._send_request(method, url, body, headers, encode_chunked)
django_1           |   File "/usr/local/lib/python3.7/http/client.py", line 1298, in _send_request
django_1           |     self.endheaders(body, encode_chunked=encode_chunked)
django_1           |   File "/usr/local/lib/python3.7/http/client.py", line 1247, in endheaders
django_1           |     self._send_output(message_body, encode_chunked=encode_chunked)
django_1           |   File "/usr/local/lib/python3.7/http/client.py", line 1026, in _send_output
django_1           |     self.send(msg)
django_1           |   File "/usr/local/lib/python3.7/http/client.py", line 966, in send
django_1           |     self.connect()
django_1           |   File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 200, in connect
django_1           |     conn = self._new_conn()
django_1           |   File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 182, in _new_conn
django_1           |     self, "Failed to establish a new connection: %s" % e
django_1           | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fce71764cd0>: Failed to establish a new connection: [Errno 110] Connection timed out


django_1           |
django_1           | During handling of the above exception, another exception occurred:
django_1           |
django_1           | Traceback (most recent call last):
django_1           |   File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
django_1           |     timeout=timeout
django_1           |   File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
django_1           |     method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
django_1           |   File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 574, in increment
django_1           |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
django_1           | urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='****', port=8000): Max retries exceeded with url: /media/zip_configuration_files/challenge_zip/3b9a15de-9047-4239-83b1-82bbdd7d5aa4.zip (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fce71764cd0>: Failed to establish a new connection: [Errno 110] Connection timed out'))
django_1           |
django_1           | During handling of the above exception, another exception occurred:
django_1           |
django_1           | Traceback (most recent call last):
django_1           |   File "/code/apps/challenges/views.py", line 822, in create_challenge_using_zip_file
django_1           |     response = requests.get(uploaded_zip_file_path, stream=True)
django_1           |   File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 75, in get
django_1           |     return request('get', url, params=params, **kwargs)
django_1           |   File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 61, in request
django_1           |     return session.request(method=method, url=url, **kwargs)
django_1           |   File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
django_1           |     resp = self.send(prep, **send_kwargs)
django_1           |   File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
django_1           |     r = adapter.send(request, **kwargs)
django_1           |   File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
django_1           |     raise ConnectionError(e, request=request)
django_1           | requests.exceptions.ConnectionError: HTTPConnectionPool(host='****', port=8000): Max retries exceeded with url: /media/zip_configuration_files/challenge_zip/3b9a15de-9047-4239-83b1-82bbdd7d5aa4.zip (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fce71764cd0>: Failed to establish a new connection: [Errno 110] Connection timed out'))
django_1           | [pid: 32|app: 0|req: 32/52] 217.170.246.111 () {44 vars in 939 bytes} [Mon Aug 30 09:34:46 2021] POST /api/challenges/challenge/challenge_host_team/1/zip_upload/ => generated 79 bytes in 130604 msecs (HTTP/1.1 406) 6 headers in 180 bytes (71 switches on core 0)

```

I cant understand what the problem is. Any help is appreciated.

**Comment by chihfanhsu** [comment]
I have the same problem. The .zip file is correctly uploaded. It seems the uploaded file cannot be correctly decompressed. I am still finding a solution.

**Comment by RishabhJain2018** [comment]
Closing this since it is a very old issue.
