### ISSUE TITLE
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. 

### ISSUE THREAD

**Issue by HuangDihe** [Cloud-CV/EvalAI#3655]
Traceback (most recent call last):
  File "/usr/local/bin/evalai", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 676, in main
    _verify_python3_env()
  File "/usr/local/lib/python3.6/site-packages/click/_unicodefun.py", line 118, in _verify_python3_env
    'for mitigation steps.' + extra)
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment.  Consult http://click.pocoo.org/python3/for mitigation steps.

**Comment by Ram81** [comment]
Closing this issue as it doesn;t have sufficient details
