### ISSUE TITLE
An circular reference error in `submission_worker.py` during evaluation

### ISSUE THREAD

**Issue by AkariAsai** [Cloud-CV/EvalAI#3710]
Hi EvalAI team,

We're trying to host a challenge for a question answering shared task at our NAACL Workshop 2022, but all of the submissions I tried by myself to test evaluation scripts failed because of a circular reference detected in [`submission_worker.py`](https://github.com/Cloud-CV/EvalAI/blob/master/scripts/workers/submission_worker.py). I run the evaluation script by myself following [the section in README](https://github.com/Cloud-CV/EvalAI-Starters#test-your-evaluation-script-locally) instruction and it worked perfectly. 
Please see the error message below. 
```
[2022-03-17 20:14:13] INFO WORKER_LOG Processing message body: {"challenge_pk": 1638, "phase_pk": 3235, "submission_pk": 184979, "is_static_dataset_code_upload_submission": false}
[2022-03-17 20:14:13] INFO SUBMISSION_LOG [x] Received submission message {"challenge_pk": 1638, "phase_pk": 3235, "submission_pk": 184979, "is_static_dataset_code_upload_submission": false}
[2022-03-17 20:14:24] ERROR SUBMISSION_LOG Exception while receiving message from submission queue with error Circular reference detected
Traceback (most recent call last):
File "/code/scripts/workers/submission_worker.py", line 712, in process_submission_callback
process_submission_message(body)
File "/code/scripts/workers/submission_worker.py", line 679, in process_submission_message
user_annotation_file_path,
File "/code/scripts/workers/submission_worker.py", line 609, in run_submission
submission_result = json.dumps(submission_result)
File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
return _default_encoder.encode(obj)
File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
chunks = self.iterencode(o, _one_shot=True)
File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
return _iterencode(o, 0)
ValueError: Circular reference detected
```
Our challenge: [challenge-page/1638/overview](https://eval.ai/web/challenges/challenge-page/1638/overview)
Github repository: [MIA-Shared-Task-2022_EvalAI](https://github.com/mia-workshop/MIA-Shared-Task-2022_EvalAI)
Could you help us to figure out what happens? Our competition is already kicked off and we will release our test data soon, so we need some help immediately. 
We really appreciate your help!

**Comment by AkariAsai** [comment]
The error has been solved and I close this issue.
