### ISSUE TITLE
evalai_nodejs_1 fails to start with error: Required path doesn't exist: /code/bower_components/trix/dist/trix.css trix

### ISSUE THREAD

**Issue by JsnowyXu** [Cloud-CV/EvalAI#3834]
- the expected behaviour
All containers in evalai should run successfully.
- the observed behaviour
![image](https://user-images.githubusercontent.com/15681176/202961262-0ce10cf1-1e94-413f-a36b-e47e0e3035ae.png)

- steps to reproduce the problem
docker-compose up --build
can not visit localhost:8888
- which operating system and/or browser you're using, if relevant
Edge / Chrom
- (if possible) copies of the console/server logs
[02:50:47] 'dev:runserver' errored after 16 ms
nodejs_1           | [02:59:13] Using gulpfile /code/gulpfile.js
nodejs_1           | [02:59:13] Starting 'dev:runserver'...
nodejs_1           | [02:59:13] Starting 'clean'...
nodejs_1           | [02:59:13] Finished 'clean' after 3.43 ms
nodejs_1           | [02:59:13] Starting '<anonymous>'...
nodejs_1           | [02:59:13] Finished '<anonymous>' after 524 μs
nodejs_1           | [02:59:13] Starting 'vendorcss'...
nodejs_1           | [02:59:13] Starting 'vendorjs'...
nodejs_1           | [02:59:13] Starting 'css'...
nodejs_1           | [02:59:13] Starting 'js'...
nodejs_1           | [02:59:13] Starting 'html'...
nodejs_1           | [02:59:13] Starting 'images'...
nodejs_1           | [02:59:13] Starting 'fonts'...
nodejs_1           | Required path doesn't exist: /code/bower_components/trix/dist/trix.css trix
nodejs_1           | [02:59:13] 'vendorcss' errored after 4.31 ms
nodejs_1           | [02:59:13] Error: Promise rejected without Error
nodejs_1           |     at Domain.onError (/usr/local/lib/node_modules/gulp/node_modules/async-done/index.js:49:15)
nodejs_1           |     at Object.onceWrapper (events.js:520:26)
nodejs_1           |     at Domain.emit (events.js:400:28)
nodejs_1           |     at Domain.emit (domain.js:475:12)
nodejs_1           |     at Domain._errorHandler (domain.js:285:21)
nodejs_1           |     at Object.<anonymous> (domain.js:172:29)
nodejs_1           |     at process._fatalException (internal/process/execution.js:166:29)
nodejs_1           | [02:59:13] 'dev:runserver' errored after 12 ms
nodejs_1           | [03:06:51] Using gulpfile /code/gulpfile.js
nodejs_1           | [03:06:51] Starting 'dev:runserver'...
nodejs_1           | [03:06:51] Starting 'clean'...
nodejs_1           | [03:06:51] Finished 'clean' after 4.03 ms
nodejs_1           | [03:06:51] Starting '<anonymous>'...
nodejs_1           | [03:06:51] Finished '<anonymous>' after 2.88 ms
nodejs_1           | [03:06:51] Starting 'vendorcss'...
nodejs_1           | [03:06:51] Starting 'vendorjs'...
nodejs_1           | [03:06:51] Starting 'css'...
nodejs_1           | [03:06:51] Starting 'js'...
nodejs_1           | [03:06:51] Starting 'html'...
nodejs_1           | [03:06:51] Starting 'images'...
nodejs_1           | [03:06:51] Starting 'fonts'...
nodejs_1           | Required path doesn't exist: /code/bower_components/trix/dist/trix.css trix
nodejs_1           | [03:06:51] 'vendorcss' errored after 7.05 ms
nodejs_1           | [03:06:51] Error: Promise rejected without Error
nodejs_1           |     at Domain.onError (/usr/local/lib/node_modules/gulp/node_modules/async-done/index.js:49:15)
nodejs_1           |     at Object.onceWrapper (events.js:520:26)
nodejs_1           |     at Domain.emit (events.js:400:28)
nodejs_1           |     at Domain.emit (domain.js:475:12)
nodejs_1           |     at Domain._errorHandler (domain.js:285:21)
nodejs_1           |     at Object.<anonymous> (domain.js:172:29)
nodejs_1           |     at process._fatalException (internal/process/execution.js:166:29)
nodejs_1           | [03:06:51] 'dev:runserver' errored after 19 ms
evalai_nodejs_1 exited with code 1

I checked the bower.json. It does not contain the trix package. I really have no clue. Please help me to figure it out.
Thanks so much!

**Comment by Ilyushin** [comment]
I have the same problem.

**Comment by gchhablani** [comment]
@Ilyushin @JsnowyXu

Hi,
We are aware of this issue and have figured out a across a solution for it. This is due to a package deprecation. 
Once we test the fix, it will be added to the repository.

CC @Ram81

**Comment by Ilyushin** [comment]
@gchhablani 
Hi, thanks. I have created the PR with solution.

https://github.com/Cloud-CV/EvalAI/pull/3838

**Comment by vpozdnyakov** [comment]
did anyone find a solution?

**Comment by RishabhJain2018** [comment]
Closing this since it is already fixed!
