### ISSUE TITLE
Fix manage EC2 instance API

### ISSUE THREAD

**Issue by gchhablani** [Cloud-CV/EvalAI#4127]
If instance ID does not exist, the APIs throw error.

```
Traceback (most recent call last):
  File "/home/ubuntu/Projects/EvalAI/scripts/monitoring/auto_scale_ec2_workers.py", line 123, in <module>
    start_job()
  File "/home/ubuntu/Projects/EvalAI/scripts/monitoring/auto_scale_ec2_workers.py", line 113, in start_job
    start_or_stop_workers_for_challenges(response, metrics, evalai_interface)
  File "/home/ubuntu/Projects/EvalAI/scripts/monitoring/auto_scale_ec2_workers.py", line 100, in start_or_stop_workers_for_challenges
    start_or_stop_workers(challenge, metrics[str(challenge["id"])], evalai_interface)
  File "/home/ubuntu/Projects/EvalAI/scripts/monitoring/auto_scale_ec2_workers.py", line 91, in start_or_stop_workers
    stop_instance(challenge, evalai_interface)
  File "/home/ubuntu/Projects/EvalAI/scripts/monitoring/auto_scale_ec2_workers.py", line 41, in stop_instance
    response = evalai_interface.stop_challenge_ec2_instance(challenge["id"])
  File "/home/ubuntu/Projects/EvalAI/scripts/monitoring/evalai_interface.py", line 165, in stop_challenge_ec2_instance
    response = self.make_request(url, "PUT")
  File "/home/ubuntu/Projects/EvalAI/scripts/monitoring/evalai_interface.py", line 42, in make_request
    response.raise_for_status()
  File "/home/ubuntu/venv/lib/python3.6/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 406 Client Error: Not Acceptable for url: https://eval.ai/api/challenges/1989/manage_ec2_instance/stop/
```

**Comment by hardikbhatia777** [comment]
Hello, is it viable to simply log the information whenever an HTTPError occurs if instance ID doesn't exist, as done in line 36?

 
```
 def make_request(self, url, method, data=None):
        headers = self.get_request_headers()
        try:
            response = requests.request(
                method=method, url=url, headers=headers, data=data
            )
            response.raise_for_status()
        except requests.exceptions.RequestException:
            logger.info(
                "The worker is not able to establish connection with EvalAI"
            )
            raise
        return response.json()?

```

We can add an extra else statement so that it doesn't throw an error entirely or maybe return a default response?
