### ISSUE TITLE
Unable to create new challenge: Unauthorized for url

### ISSUE THREAD

**Issue by RonaldEnsing** [Cloud-CV/EvalAI#4278]
I am following the instructions from https://eval.ai/web/challenge-create and https://evalai.readthedocs.io/en/latest/host_challenge.html#host-challenge-using-github to host a challenge on https://eval.ai, but I am getting the following error during the Actions in the build step during 'Validate challenge': 
```
Traceback (most recent call last):
  File "github/challenge_processing_script.py", line 74, in <module>
    response.raise_for_status()
  File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://eval.ai/api/challenges/challenge/challenge_host_team/3109/validate_challenge_config/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "github/challenge_processing_script.py", line 81, in <module>
    error = response.json()["error"]
KeyError: 'error'
Error: Process completed with exit code 1.
```

**Comment by SondosBsharat** [comment]
Have you solved the issue ? because I am having the same problem

**Comment by imprs** [comment]
I ran into this issue and realised that my EvalAI token had expired. You can check if your token is still valid in _Profile_ -> _Auth Token_ and if it is expired, try generating a new one with _Refresh Token_.

The error message could have been informative.

**Comment by RishabhJain2018** [comment]
Hi @imprs , Thanks for the fix and the feedback. We will fix the error message. I am closing this one since I opened another issue for it.
