### ISSUE TITLE
Fails to build docker image for M1 ( ARM ) macbook. Unable to start application. 

### ISSUE THREAD

**Issue by susanka068** [Cloud-CV/EvalAI#4379]
system : apple macbook m1 ( ARM based )

I have run `docker-compose up` in my terminal. it fails to build an image. at first it failing to install google-chrome-stable. after a bit of googling in found out there is no google-chrome for arm based machine. 

check [here](https://stackoverflow.com/a/74155249)

so I explicitly added `--platform=linux/amd64`.

but now I am having issues to installing requirements of dev.txt

```
#0 39.06 Collecting django-autofixture==0.12.1 (from -r dev.txt (line 7))
#0 39.14   Downloading django-autofixture-0.12.1.tar.gz (29 kB)
#0 39.17   Preparing metadata (setup.py): started
#0 39.35   Preparing metadata (setup.py): finished with status 'error'
#0 39.38   error: subprocess-exited-with-error
#0 39.38   
#0 39.38   × python setup.py egg_info did not run successfully.
#0 39.38   │ exit code: 1
#0 39.38   ╰─> [29 lines of output]
#0 39.38       running egg_info
#0 39.38       creating /tmp/pip-pip-egg-info-a_emu9da/django_autofixture.egg-info
#0 39.38       writing /tmp/pip-pip-egg-info-a_emu9da/django_autofixture.egg-info/PKG-INFO
#0 39.38       Traceback (most recent call last):
#0 39.38         File "<string>", line 36, in <module>
#0 39.38         File "<pip-setuptools-caller>", line 34, in <module>
#0 39.38         File "/tmp/pip-install-q902pdg8/django-autofixture_f5d6c23acc434640876ce2872fec0236/setup.py", line 76, in <module>
#0 39.38           test_suite = 'runtests.runtests',
#0 39.38         File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 107, in setup
#0 39.38           return distutils.core.setup(**attrs)
#0 39.38         File "/usr/local/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
#0 39.38           return run_commands(dist)
#0 39.38         File "/usr/local/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
#0 39.38           dist.run_commands()
#0 39.38         File "/usr/local/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
#0 39.38           self.run_command(cmd)
#0 39.38         File "/usr/local/lib/python3.7/site-packages/setuptools/dist.py", line 1234, in run_command
#0 39.38           super().run_command(command)
#0 39.38         File "/usr/local/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
#0 39.38           cmd_obj.run()
#0 39.38         File "/usr/local/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 307, in run
#0 39.38           writer(self, ep.name, os.path.join(self.egg_info, ep.name))
#0 39.38         File "/usr/local/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 677, in write_pkg_info
#0 39.38           metadata.write_pkg_info(cmd.egg_info)
#0 39.38         File "/usr/local/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 1137, in write_pkg_info
#0 39.38           self.write_pkg_file(pkg_info)
#0 39.38         File "/usr/local/lib/python3.7/site-packages/setuptools/dist.py", line 227, in write_pkg_file
#0 39.38           if not long_description.endswith("\n"):
#0 39.38       AttributeError: 'UltraMagicString' object has no attribute 'endswith'
#0 39.38       [end of output]
#0 39.38   
#0 39.38   note: This error originates from a subprocess, and is likely not a problem with pip.
#0 39.38 error: metadata-generation-failed
#0 39.38 
#0 39.38 × Encountered error while generating package metadata.
```

**Comment by RishabhJain2018** [comment]
Closing this since #4498 solves this.
