### ISSUE TITLE
Frontend: Gulp watch task is breaking 

### ISSUE THREAD

**Issue by anweshknayak** [Cloud-CV/EvalAI#599]
@aka-jain

**Comment by spyshiv** [comment]
can you elaborate ?

**Comment by aka-jain** [comment]
@anweshknayak  I think we don't have gulp watch task now. We have already merged all the tasks to a single task and named as gulp dev:runserver. Please check readme.

**Comment by anweshknayak** [comment]
@aka-jain Yes Im aware of that. See this 

 'vendorjs' errored after 342 ms
[17:21:47] Error: watch /home/anwesh/new/EvalAI/bower_components/angular-material/ ENOSPC
    at exports._errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1429:19)
    at Object.fs.watch (fs.js:1456:11)
    at Gaze._watchDir (/home/anwesh/new/EvalAI/node_modules/gaze/lib/gaze.js:289:30)

**Comment by anweshknayak** [comment]
http://stackoverflow.com/a/32600959

Solved.
